name: llb CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install libssl + openssl
      run: sudo apt-get install libssl-dev openssl
    - name: cmake
      run: cmake .
    - name: make
      run: make
